Update the hero description files
rm-controls/rm_description pull request #11
Opened 2022-03-28 12:33 UTC by Edwinlinks

2022-03-28 12:44 UTC, Edwinlinks commented
pre-commit 没过，在修，今晚修完。

2022-03-29 04:22 UTC, qiayuanliao commented
需要提供截图

2022-03-30 04:43 UTC, qiayuanliao requested changes
@Edwinlinks 回复消息！

2022-03-30 08:41 UTC, Edwinlinks commented
英雄惯量视图
![hero_ineria](https://user-images.githubusercontent.com/74891319/160788460-0016f1b9-73e3-4dab-ab9c-8a0bef5aec2c.png)
![hero_ineria_1](https://user-images.githubusercontent.com/74891319/160788567-b6bfe064-4ae8-4cd1-b616-d5404188d163.png)
pitch质心位置
![pitch](https://user-images.githubusercontent.com/74891319/160788595-6102b20a-8b2c-467b-801d-8ae733851f45.png)
yaw质心位置
![yaw](https://user-images.githubusercontent.com/74891319/160789039-7152c46e-53b7-4bb7-b684-9436dac11a1b.png)

2022-03-30 08:42 UTC, Edwinlinks commented
英雄惯量视图
![hero_ineria_1](https://user-images.githubusercontent.com/74891319/160789769-3c545d98-fafc-42af-a4c1-eabc69f986a3.png)
![hero_ineria](https://user-images.githubusercontent.com/74891319/160789757-4160e6f4-5de0-4356-98cb-ff7786ddb294.png)
pitch质心位置
![pitch](https://user-images.githubusercontent.com/74891319/160789845-719455b7-af06-4535-bc39-772438988af2.png)
yaw质心位置
![yaw](https://user-images.githubusercontent.com/74891319/160789888-e6c3b1ff-de37-470f-9034-30249ff99505.png)
碰撞
![hero_colli](https://user-images.githubusercontent.com/74891319/160789950-96a1ad9f-6840-4958-b46d-44b06f6b4be9.png)

2022-03-30 11:38 UTC, qiayuanliao approved these changes

2022-03-30 11:38 UTC, merged